---
title: Resume
output:
    html_document:
        css: style.css
---

```{r setup, include = FALSE}
source("scripts/sass.R")
```

<div class=header-flex-container>
# Alec Wong
</div>

# <span class=section-header>Professional Experience</span> {.section-box}

## Progressive Casualty Insurance -- *Lead Data Analyst* {.company-box .pgr-box}

2019 - Present | 2022 - Present (at Lead level)

### Highlighted role achievements

<div class='company-bullets'>
- Replaced tabular estimation of core team metrics with statistical models, reducing run-time and providing a framework to interpret variable effects and model parsimony.
- Modeled claims adjuster productivity using zero-inflated negative binomial GLM using R package `pscl` as well as non-linear mixed-effects modeling with R package `brms`, developing theory for an alternative staffing criterion.
- Forecasted risk of when claim ID numbers might exceed limits using Bayesian generalized linear regression with R package `rstanarm`, providing a recommended date for the start of a large-scale effort to increase claim ID size.
- Increased efficiency by approximately 80 FTE using a data pipeline in python to quantify auto inspector drive times using location information and Google Maps Distance Matrix API.
- Improved team efficiency by creating an interactive framework in the form of a web application for comparing adjustments to our staff model, abstracting a previously labor-intensive manual process.
- Recast central team SQL dataset using delta compression to reduce storage size by over 5x and reduce analyst time spent writing lengthy and repetitive queries.
- Experienced in several SQL frameworks (TSQL, DB2, Snowflake, SQLite, duckdb) creating complex queries joining several tables each with hundreds of millions of records.
</div>

### Contributions additional to role

<div class='company-bullets'>
- Won 1st Prize in the 2024 Inviztational, a company-wide visualization challenge for a prize of $2000, presenting a dynamic visualization displaying satellite imagery of hurricanes over their lifespan.
- Developed and taught a curriculum for a dual R and Python course to 25 attendees over a 9 month period.
- Enforced code best-practices, introduced collaborative git workflows to our team, and checked critical code into Github repositories.
- Developed several R and python packages including tools to eliminate boilerplate in SQL connections, extend `ggplot2` with a company color palette, and other miscellaneous functions.
- Spent over 100 hours between 2021 and 2024 providing one-on-one support to analysts all over the company supporting R, Python, and SQL questions.
- Led bi-weekly R Clinic support sessions as the R SME for Progressive (ongoing).
- Assisted in testing of Posit corporate productivity software, as well as an in-house python cloud platform.
- Won 2nd place in SPrize 2021, a company-wide predictive modeling challenge, involving over 15 teams.
</div>

## Cornell University -- *Graduate Research Assistant* {.company-box .cornell-box}

2015 - 2018

<div class='company-bullets'>
- Gained competency with Bayesian inference using Markov Chain Monte Carlo (MCMC) simulation, geostatistical modeling, maximum likelihood optimization procedures, and generalized linear models.
- Developed two novel statistical models that use MCMC to estimate animal population size and relationships with spatial habitat covariates, applied to moose in New York.
- The statistical models' performance was tested via simulation analysis using high-performance computing techniques under an original dual-layer parallelization scheme of a cluster of computers.
- Applied motivational and effective leadership leading field research teams of up to 10 personnel into wilderness conditions, and led laboratory discussions on the use of Git and R Markdown to improve organization of research.
- Communicated results to statistical and ecological audiences nationally and internationally.
</div>

<div class=bottom-grid>

# <span class=section-header>Education</span> {.section-box .bottom-grid-item}

* **Cornell University**, Ithaca, NY
    * M.S. Quantitative Ecology. 2018. GPA: 4.0
    * Thesis: [Methodologies for abundance estimation of moose (*Alces alces*) and other rare species](https://drive.google.com/file/d/18yUIGAyi5ypOhyEOd3BlsLt-20M1R2LC/view)
* **University of Nebraska**, Lincoln, NE
    * B.S. Fisheries and Wildlife. 2013. GPA: 3.84 *cum laude*
    * Minor: Mathematics

# <span class=section-header>Public Engagement</span> {.section-box .bottom-grid-item}

### 2024 - Present ["Data Laundry" data cleaning & exploration series](https://github.com/awong234/laundry-day)
### 2022 - Present [Co-organizer of the Cleveland R User Group](https://www.meetup.com/cleveland-user-group/)
### 2021 ["You’re a Parselmouth, Harry! Speaking python inside of R workflows" -- satRday Columbus, Cleveland R User Group](https://www.youtube.com/watch?v=rAvPJzCKCCg)
### 2020 ["sARcASm: Practicing programming techniques via an R package" -- satRday Columbus](https://www.youtube.com/watch?v=_ulDpEcjZEA)
### 2019 ["Project Organization: Head-Ache to GNU Make" -- Cleveland R User Group](https://www.youtube.com/watch?v=dCkHqzotzsQ)

</div>

<div class=bottom-grid>

# <span class=section-header>Software</span> {.section-box .bottom-grid-item}

* R (since 2014. Uses: statistical analysis, package development, web app development)
* Python (since 2019. Uses: ETL, web API's, automation, deep learning)
* Git
* SQL
* Front-end development (HTML, CSS, JavaScript)
* Tableau / Power BI
* ArcGIS

# <span class=section-header>Open-Source Contributions</span> {.section-box .bottom-grid-item}

<div class=bottom-grid>

## Pull-requests

* [`keyring` (merged)](https://github.com/r-lib/keyring/pull/88)
* [`import` (merged)](https://github.com/rticulate/import/pull/55)
* [`emphatic` (merged)](https://github.com/coolbutuseless/emphatic/pull/4)
* [`boxr` (merged)](https://github.com/r-box/boxr/pull/79)
* [`novaGallery` (open)](https://github.com/novafacile/novagallery/pull/51)

## Issues

* [`import #59`](https://github.com/rticulate/import/issues/59), [dev response](https://github.com/rticulate/import/issues/56#issuecomment-1129147197)
* [`import #56`](https://github.com/rticulate/import/issues/56)
* [`dbplyr`](https://github.com/tidyverse/dbplyr/issues/553)
* [`emphatic`](https://github.com/coolbutuseless/emphatic/issues/3)
* [`glue`](https://github.com/tidyverse/glue/issues/158)
* [`novaGallery`](https://github.com/novafacile/novagallery/issues/52)

</div>

</div>

<div class=section-box>

# <span class=section-header>Code Examples</span>

## [Pytorch implementations for image and video](https://github.com/awong234/torch-for-image-and-video)

* An exploration of neural network architectures for image and video.
* Tasks explored: image generation/completion, regression from video input.
* Key lessons: data loaders, model training, model evaluation, cuda integration, U-Net, network visualization

## [Advent of Code](https://github.com/awong234/advent_of_code)

* Ranked second out of 14 participating data scientists and BI developers on the company leaderboard.
* Primarily interested in solving puzzles with `awk` to enhance programming skills with linux tools.
* Selected entries (2021):
    * [R6 structures and matrix operations](https://github.com/awong234/advent_of_code/tree/main/2021/day_06)
    * Visualized 2021 Day 9 solution with the `rayshader` R package [link](https://github.com/awong234/advent_of_code/blob/main/2021/day_09/readme.md).

## [Automated internet speed tests, hosted on my website](https://alecsalces.com/speedtest/)

* [Source code.](https://github.com/awong234/speedtest)
* Tests speeds daily and updates website.
* Displays data with D3.

## [This resume!](https://github.com/awong234/Resume)

* Follows a `make` workflow to generate the output files. Just run `make` to compile everything!
* Uses `rmd`, `scss`, `pandoc`, and `wkhtmltopdf` to create the document.

</div>

<div class=footer>
Last update: `r format(Sys.time(), '%Y-%m-%d')`
</div>
